name: rafbl
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - rdkit=2022.9.5
  - pip=22.2.2
  - numpy=1.24
  - scipy=1.10
  - pandas=2.0
  - scikit-learn=1.2
  - pip:
      - chemiscope
      - morfeus-ml
      - rmsd
      - ase
      - libarvo
      - networkx
      - pymatgen

